name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 1.5.2
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter_core:
    git:
      url: https://github.com/Saurabh-Detharia/stream-chat-flutter.git
      ref: fixes
      path: packages/stream_chat_flutter_core
  photo_view: ^0.11.1
  rxdart: ^0.25.0
  scrollable_positioned_list: ^0.1.10
  jiffy: ^4.1.0
  flutter_svg: ^0.21.0
  flutter_portal: ^0.3.0
  cached_network_image: ^2.5.1
  shimmer: ^2.0.0
  flutter_markdown: ^0.6.1
  url_launcher: ^6.0.3
  emojis: ^0.9.3
  video_player: ^2.1.1
  chewie: ^1.0.0
  file_picker: ^3.0.1
  image_picker: ^0.7.4
  flutter_keyboard_visibility: ^5.0.1
  video_compress: ^3.0.0
  visibility_detector: ^0.2.0
  meta: ^1.3.0
  lottie: ^1.0.1
  substring_highlight: ^1.0.26
  flutter_slidable: ^0.6.0
  image_gallery_saver: ^1.6.9
  share_plus: ^2.0.0
  photo_manager: ^1.1.4
  ezanimation: ^0.5.0
  synchronized: ^3.0.0
  characters: ^1.1.0
  dio: ^3.0.10
  path_provider: ^2.0.1
  video_thumbnail: ^0.3.3

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5
  pedantic: ^1.11.0